/var/log/tradingbot.log {
    weekly
    rotate 8
    compress
    missingok
    notifempty
    copytruncate
}

/opt/tradingbot/logs/*.log {
    weekly
    rotate 8
    compress
    missingok
    notifempty
    copytruncate
    su ubuntu ubuntu
}
